git:
  depth: 100

language: generic

env:
  global:
    - PYENV_VERSION=3.6
    #- CHANS_DEV="-c pyviz/label/dev -c ioam -c bokeh -c erdc -c defaults"
    #- CHANS_REL="-c pyviz -c erdc -c defaults"
    - LABELS_DEV="--label dev"
    - LABELS_REL="--label dev --label main"

stages:
  - test
#  - name: doc
#    if: branch = master AND type != pull_request

#cache:
#  directories:
#    - $HOME/miniconda
#
#before_cache:
#  - rm -rf $HOME/miniconda/pkgs
#  - rm -rf $HOME/miniconda/conda-bld/*
#  - rm -rf $HOME/miniconda/envs/*/conda-bld

# quick hack to determine what tag is (improvements welcomed)
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

jobs:
  include:

    ########## TEST DEVELOPER INSTALL ##########

    - &default
      stage: test
      before_install: true
      install:
        #####
        # install doit/pyctdev and use to install miniconda...
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        # ...and now install doit/pyctdev into miniconda
        - conda install -c pyviz/label/dev pyctdev && doit ecosystem_setup
        #####

        # channel pins in env file not respected until 4.6, which
        # isn't out yet. channel pins in recipe don't carry through to built package. (we'll need to make a pkg or provide a package
        # listing file for conda i.e. not use conda env)
        #- conda install --channel "conda-canary" conda
        #- doit env_create $CHANS_DEV --python=$PYENV_VERSION
        #- doit develop_install $CHANS_DEV -o recommended
        - conda config --set path_conflict warn
        - conda create -n earthsim -c pyviz/label/dev -c ceball -c pyviz -c conda-forge -c defaults -c erdc --file=earthsim-env conda-forge::python=3.6
        - source activate earthsim
        - conda remove --force holoviews geoviews geoviews-core
        - pip install git+https://github.com/ioam/holoviews.git
        - pip install git+https://github.com/ioam/geoviews.git
        - pip install -e . --no-deps
        - doit env_capture
      script:
        - earthsim fetch-data --path=examples
        - travis_wait 60 doit test_all

    - <<: *default
      os: osx
      osx_image: xcode9.3
      env: PYENV_VERSION=3.6.4
      before_install:
        # set up python
        - eval "$(pyenv init -)"
        - pyenv install $PYENV_VERSION  
        # check the below still required
        # brew-installed geos interferes with cartopy?
        - brew uninstall --ignore-dependencies geos gdal postgis

    ########## DOCS ##########

#    - <<: *default
#      stage: doc
#      script:
#        - doit install_doc_dependencies
#        - doit download_sample_data
#        - travis_wait 60 doit docs
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $GITHUB_TOKEN
#        local_dir: ./doc/_build/html
