git:
  depth: 100

language: generic

env:
  global:
    - PYENV_VERSION=3.6

# TODO before merge: temporarily testing doc building on this branch
stages:
  - test
  - name: doc
    if: branch = switch_to_pyct2
#    if: branch = master AND type != pull_request

jobs:
  include:

    ########## TEST DEVELOPER INSTALL ##########

    - &default
      stage: test
      before_install: true
      install:
        #####
        # install doit/pyctdev and use to install miniconda...
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        # ...and now install doit/pyctdev into miniconda
        - conda install -c pyviz/label/dev pyctdev && doit ecosystem_setup
        #####
        - conda config --set path_conflict warn
        - conda create -n earthsim -c pyviz/label/earthsim -c conda-forge --file=dependencies.txt conda-forge::python=3.6
        - source activate earthsim
        - pip install -e . --no-deps
        - doit env_capture
      script:
        - earthsim fetch-data --path=examples
        - travis_wait 60 doit test_all

    - <<: *default
      os: osx
      osx_image: xcode9.3
      env: PYENV_VERSION=3.6.4
      before_install:
        # set up python
        - eval "$(pyenv init -)"
        - pyenv install $PYENV_VERSION  
        # check the below still required
        # brew-installed geos interferes with cartopy?
        - brew uninstall --ignore-dependencies geos gdal postgis

    ########## DOCS ##########

    - <<: *default
      stage: doc
      script:
        - conda install -c pyviz/label/dev -c conda-forge nbsite sphinx_ioam_theme
        - earthsim fetch-data --path=examples
        - travis_wait 60 doit docs
# see comment by 'stages' above
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $GITHUB_TOKEN
#        local_dir: ./doc/_build/html
#        fqdn: earthsim.pyviz.org
