language: generic

stages:
  - test
  - name: doc
    if: branch = master AND type != pull_request

before_install:
  - echo -e "machine github.com\n  login $CI_USER\n  password $CI_USER_PASSWORD" >> ~/.netrc

jobs:
  include:
    - &default
      stage: test
      os: linux
      install:
        #######################
        ## install miniconda ##
        - easy_install --user doit==0.29.0 ioamdoit
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            ~/Library/Python/2.7/bin/doit install_miniconda;
          else
            ~/.local/bin/doit install_miniconda;
          fi
        - rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda config --set path_conflict prevent
        #######################
        - pip install ioamdoit
        - conda env create
        - source activate earthsim
        - doit develop_install
        ###
        # TODO: figure out what's depending on (deprecated?) gcc package; see https://github.com/pyviz/EarthSim/issues/97
        - pushd /home/travis/miniconda/envs/earthsim/lib/ && rm -rf libstdc++.so.6 && ln -s libstdc++.so.6.0.24 libstdc++.so.6 && popd
        #- conda remove -y --force gcc
        #- conda install -y --force -c conda-forge libgcc-ng scipy numpy libstdcxx-ng
        ###
        - doit capture_conda_env
      script:
        - doit download_sample_data
        - travis_wait 60 doit all_tests

# restore when travis/macos recovers...
#    - <<: *default
#      os: osx
#      before_install:
#        # brew-installed geos interferes with cartopy?
#        - brew uninstall --ignore-dependencies geos gdal postgis
#      if: branch = master AND type != pull_request

    - <<: *default
      stage: doc
      script:
        - doit install_doc_dependencies
        - doit download_sample_data
        ##
        # see github.com/pyviz/EarthSim/issues/113
        - rm -rf examples/topics/batched_example/*.ipynb
        - rm -rf examples/topics/GSSHA_Parameter_Sweep.ipynb
        ##
        - travis_wait 60 doit docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/_build/html
