language: generic

stages:
  - test
  - name: doc
    if: branch = master AND type != pull_request

jobs:
  include:
    - &default
      stage: test
      os: linux
      install:
        #######################
        ## install miniconda ##
        - easy_install --user doit==0.29.0 ioamdoit
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            ~/Library/Python/2.7/bin/doit install_miniconda;
          else
            ~/.local/bin/doit install_miniconda;
          fi
        - rm -f .doit.db
        - export PATH="$HOME/miniconda/bin:$PATH"
        #######################
        - pip install ioamdoit
        - conda env create -q
        - source activate earthsim
        - doit capture_conda_env
      script:
        - doit develop_install
        - doit all_tests

    - <<: *default
      os: osx
      before_install:
        # brew-installed geos interferes with cartopy?
        - brew uninstall --ignore-dependencies geos gdal postgis
      if: branch = master AND type != pull_request

    - <<: *default
      stage: doc
      script:
        - doit develop_install
        - doit install_doc_dependencies
        - doit docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./doc/_build/html
        #on:
        #  tags: true
