name: earthsim
channels:
    - pyviz/label/dev
    - conda-forge
    - defaults
    - erdc
    - ceball
dependencies:

    ########### direct deps
    - conda-forge::python=3.6
    - conda-forge::fiona
    - conda-forge::gdal
    - conda-forge::cartopy
    - conda-forge::bokeh
    - conda-forge::xarray
    - conda-forge::geopandas
    - conda-forge::jupyter
    - ioam::lancet
    - conda-forge::opencv
    - conda-forge::gsshapy    
    # should move updated packaging to conda-forge or erdc
    - ceball::gssha
    - ceball::filigree

    - erdc::quest

    - pyviz/label/dev::datashader
    - pyviz/label/dev::param
    - pyviz/label/dev::parambokeh
    - pyviz/label/dev::paramnb
    - pyviz/label/dev::geoviews


    ########### indirect deps
    #
    - pyviz/label/dev::pyviz_comms  # missing from parambokeh
    - conda-forge::scikit-image     # ?
    - conda-forge::descartes        # ?
    - conda-forge::numpy=1.13       # avoid warnings with numpy=1.14 and bokeh=1.12.14
    - conda-forge::scipy            # ensure scipy (and hence its deps) come from c-f
    - conda-forge::libgfortran      # (also for scipy)

    ########### for tests
    - pyviz/label/dev::nbsmoke

    - pip:
        - git+https://github.com/ioam/holoviews.git

