{% set sdata = load_setup_py_data() %}

package:
  name: earthsim
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    {% for group,epoints in sdata.get("entry_points",{}).items() %}
    {% for entry_point in epoints %}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}

requirements:
  host:
    - python
    - setuptools
    - param
  run:
    ########### direct deps
    - conda-forge::python=3.6
    - conda-forge::fiona=1.7.12
    - conda-forge::gdal=2.2.4
    - conda-forge::cartopy=0.16.0
    - conda-forge::bokeh=0.12.16
    - conda-forge::xarray=0.10.7
    - conda-forge::geopandas=0.3.0
    - conda-forge::jupyter=1.0.0
    - conda-forge::notebook=5.5.0
    - conda-forge::opencv=3.4.1
    - conda-forge::gsshapy=2.3.8
    ####
    # Should move updated packaging to erdc when done, and when source
    # is public should be moved to conda-forge
    - ceball::gssha=7.12.2+ceball
    # (lib)filigree still WIP
    - ceball::filigree=0.0.6+ceball
    - ceball::libfiligree=0.0.4+ceball
    ####
    - erdc::quest=2.4.1
    - pyviz/label/dev::datashader=0.6.6
    - pyviz/label/dev::param=1.7.0
    - pyviz/label/dev::parambokeh=0.2.3.dev8
    - pyviz/label/dev::paramnb=2.0.3
    - pyviz::holoviews
    - pyviz/label/dev::geoviews
    - conda-forge::lancet=0.9.0


    ########### indirect deps
    #
    - conda-forge::scikit-image=0.14.0 # ?
    - conda-forge::descartes=1.1.0     # ?
    - conda-forge::numpy               # ensure scipy (and its deps) come from c-f
    - conda-forge::scipy               # [not win]
#    - conda-forge::libgfortran        # (also for scipy)

test:
  imports:
    - earthsim
  requires:
    {% for dep in sdata['extras_require']['tests'] %}
    - {{ dep }}
    {% endfor %}    

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
